START TRANSACTION;


DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220512110859_add-column-to-user-table') THEN
    ALTER TABLE "user"."user" DROP COLUMN email;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220512110859_add-column-to-user-table') THEN
    DELETE FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20220512110859_add-column-to-user-table';
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220512104711_add-product-comment-table') THEN
    DROP TABLE store.product_comment;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220512104711_add-product-comment-table') THEN
    DELETE FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20220512104711_add-product-comment-table';
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220511074325_remove-test-table') THEN
    CREATE TABLE store.test (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(200) NOT NULL,
        CONSTRAINT "PK_test" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220511074325_remove-test-table') THEN
    DELETE FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20220511074325_remove-test-table';
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220511070558_add-test-table') THEN
    DROP TABLE store.test;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220511070558_add-test-table') THEN
    DELETE FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20220511070558_add-test-table';
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220510072244_init_db') THEN
    DROP TABLE store.category_product;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220510072244_init_db') THEN
    DROP TABLE store.order_position;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220510072244_init_db') THEN
    DROP TABLE "user".user_role;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220510072244_init_db') THEN
    DROP TABLE store.category;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220510072244_init_db') THEN
    DROP TABLE store.product;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220510072244_init_db') THEN
    DROP TABLE store."order";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220510072244_init_db') THEN
    DROP TABLE "user".role;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220510072244_init_db') THEN
    DROP TABLE "user"."user";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220510072244_init_db') THEN
    DELETE FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20220510072244_init_db';
    END IF;
END $EF$;
COMMIT;

