name: Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        
      - name: Show the version
        run: echo ${{ env.VERSION }}
          
      # Deployment
      
      - name: Trigger the deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "version": "${{ env.VERSION }}" }'

      # Summary

      - name: Show the summary
        run: echo "### ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY