name: Deployment for production

concurrency: production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: http://knowledge-sharing.westeurope.cloudapp.azure.com/version

    steps:
      - name: Get the version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        
      - name: Show the version
        run: echo ${{ env.VERSION }}
          
      # Deployment
      
      - name: Trigger the deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.PRODUCTION_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.PRODUCTION_WEBHOOK_SECRET }}
          data: '{ "version": "${{ env.VERSION }}" }'

      # Summary

      - name: Show the summary
        run: echo "### ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY