name: Tests by external action

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: mcr.microsoft.com/dotnet/sdk:6.0-alpine

    steps:
      - name: Test application
        uses: lrydzkowski/test-dotnet-action@v6.0
        env:
          HUSKY: 0