name: Tests by external action in container

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
    
      - name: Test application
        uses: lrydzkowski/test-dotnet-in-container-action@v6.0