name: Tests inside container

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Show OS version
        run: cat /etc/os-release
        
      - name: Show .NET version
        run: dotnet --version

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal